spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: test
  jpa:
    hibernate:
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQL8Dialect
          ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

blog:
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005
  email: mail@mail.ru
  phone: +7 903 666-44-55
  subtitle: Рассказы разработчиков
  title: DevPub

captcha:
  delete_timeout: 60 # min
  random_secret_key_length: 22
  image:
    format: png
    format_string: data:image/png;base64
    text:
      length: 3
      font:
        random_font1: SanSerif
        random_font2: Serif
        random_font3: Monospaced
    width: 100
    height: 35

user:
  password:
    validation_regex: "^.{6,}$"
    restore_pass_message_string: "/login/change-password/"
    restore_message_subject: "Ссылка для восстановление пароля"
  name:
    validation_regex: "^[а-яА-ЯёЁa-zA-Z]+$"
  image:
    upload_folder: upload
    avatars_folder: avatars
    avatars_width_size: 36
    avatars_height_size: 36
    format: jpg
    max_size: 5000000 # bytes

post:
  title:
    min_length: 3
  text:
    min_length: 150
  image:
    root_folder: images
    upload_folder: upload
    format: jpg

post_comment:
  min_length: 10