spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: test
  jpa:
    hibernate:
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQL8Dialect
          ddl-auto: validate

blog:
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005
  email: mail@mail.ru
  phone: +7 903 666-44-55
  subtitle: Рассказы разработчиков
  title: DevPub

captcha:
  delete_timeout: 60 # min
  random_secret_key_length: 22
  image:
    format: png
    format_string: data:image/png;base64
    text:
      length: 3
      font:
        random_font1: SanSerif
        random_font2: Serif
        random_font3: Monospaced
    width: 100
    height: 35

user:
  password:
    validation_regex: "^.{6,}$"
  email:
    validation_regex: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}"
  name:
    validation_regex: "^[а-яА-ЯёЁa-zA-Z]+$"